#!/usr/bin/env python3
from __future__ import annotations

import argparse
from pathlib import Path

import yaml


START = "<!-- MODULE_INDEX:START -->"
END = "<!-- MODULE_INDEX:END -->"
GENERATED = "<!-- generated by scripts/generate_module_index.py; do not edit -->"


def load_registry(path: Path) -> dict:
    with path.open("r", encoding="utf-8") as handle:
        data = yaml.safe_load(handle)
    if not isinstance(data, dict) or not isinstance(data.get("modules"), list):
        raise ValueError("modules.yaml must contain a modules list")
    return data


def render_index(registry: dict) -> str:
    lines = [START, GENERATED]
    for module in registry["modules"]:
        module_id = module["id"]
        path = module["path"].replace("\\", "/")
        label = module["route_label"].strip()
        status = module["status"]
        suffix = "" if registry.get("package_schema") == "successor-v2" else f" ({status})"
        lines.append(f"- {label} → [`{module_id}`]({path}){suffix}")
    lines.append(END)
    return "\n".join(lines)


def replace_index(skill_text: str, rendered: str) -> str:
    start = skill_text.find(START)
    end = skill_text.find(END)
    if start < 0 or end < 0 or end < start:
        raise ValueError("SKILL.md is missing valid module index markers")
    end += len(END)
    return skill_text[:start] + rendered + skill_text[end:]


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate the direct module index in SKILL.md")
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[2] / "scoville-design-anti-ai-slop")
    parser.add_argument("--check", action="store_true", help="Fail instead of writing when the index drifts")
    args = parser.parse_args()

    root = args.root.resolve()
    registry = load_registry(root / "modules.yaml")
    skill_path = root / "SKILL.md"
    current = skill_path.read_text(encoding="utf-8")
    rendered = render_index(registry)
    if registry.get("package_schema") == "successor-v2":
        rendered = rendered.replace(GENERATED + "\n", "")
    expected = replace_index(current, rendered)

    if current == expected:
        print("module index is current")
        return 0
    if args.check:
        print("module index drift detected")
        return 1

    skill_path.write_text(expected, encoding="utf-8", newline="\n")
    print("module index generated")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
